spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cars_db
    username: cars_user
    password: pass
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/cars_db
    user: cars_user
    password: pass